# Generated by Django 5.1.3 on 2024-11-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='branch',
            field=models.CharField(default='o', max_length=255),
            preserve_default=False,
        ),
    ]
